### ISSUE TITLE
Too much use space than before

### ISSUE THREAD

**Issue by mantarimay** [openSUSE-Rust/obs-service-cargo#117]
**Describe the bug**
Couple week (or month) ago, my 50GB root and under 10GB free space is enough for maintenance rust package, especially for get vendor and store it on .cargo.

but now i make a lot free space until more than 10 GB, it still not enough to finishing `osc service mr`, especially if vendor.tar.zst result large more than 50MB (if vendor.tar.zst result only 10-20MB, its no problem like [ocrs](https://build.opensuse.org/package/show/X11:Utilities/ocrs)/[resource](https://build.opensuse.org/package/show/X11:Utilities/resources))

**obs-service-cargo version (run`rpm -qa | grep obs-service-cargo`)**
obs-service-cargo-4.3.5-1.1.x86_64

**To Reproduce**
Example meli [specfile](https://build.opensuse.org/projects/home:mantarimay:apps/packages/meli/files/meli.spec?expand=1) and [_service](https://build.opensuse.org/projects/home:mantarimay:apps/packages/meli/files/_service?expand=1). 

or big vendor like [ruffle](https://build.opensuse.org/package/show/Emulators/ruffle)/[oculante](https://build.opensuse.org/package/show/graphics/oculante), i will get this issue.

1. Do `osc service mr` or `osc service ra`

**Expected behavior**
Do not use free space too much. now i back to use `cargo vendor`  to temporary fix this issue. i wish i can  `osc service mr` or `osc service ra` like before. 

**Additional context**
![Screenshot from 2024-12-03 03-07-53](https://github.com/user-attachments/assets/da28f728-2226-47b7-976e-ca60d49f288e)

**Comment by uncomfyhalomacro** [comment]
Hi there @mantarimay. I am not sure how or why you have this issue. Based from what I see, it seems the available space that you have is about **13.4G** from the screenshot. I am not sure what factors that you get a "No space left on device". I also vendor larger files such as those from [deno](https://build.opensuse.org/package/show/devel:languages:javascript/deno). I would like to know if you are using a container for this operation.

**Comment by uncomfyhalomacro** [comment]
I would like to ask you to do these for me
- Delete `$CARGO_HOME/registry` which is located usually at `~/.cargo/registry`.
- Run `cargo vendor` on a crate that has a large vendor.
- Run `dust` in `$CARGO_HOME/registry`.
- Give screenshot or output of the result of `dust` command.

Example:
![image](https://github.com/user-attachments/assets/4f9c3507-0564-4a2b-8dc8-f5f37a949251)

**Comment by uncomfyhalomacro** [comment]
What concerns me is your filesystem. I am not sure if `duf` has really reflected the **real size** used, btrfs always has this issue about not really giving the actual size.

I use xfs for my `/home` partition because I have bad experiences with btrfs for `/home`.

**Comment by uncomfyhalomacro** [comment]
I still have this suspicion that this is really a BTRFS issue because
1. 13.4G is still enough for a 50MB vendor tarball. For example, the total size of the `registry.tar.zst` tarball for deno is about 137MB. Decompressed + extracted size is about 194MB. 
2. I still don't understand how 13.4G is not enough and why running `cargo vendor` from `obs-service-cargo` exhausts your storage. Maybe I am not looking at the other factors such as FS swappiness and RAM usage.
3. Going back to point 1.

As much as I want to look and find a fix into this issue ASAP, this information (not you) for me is really lacking and needs more attention.

I tried reproducing your issue and it does seem to work without issues on my side. I still lean on the suspicion that it really is because BTRFS is reporting falsely about your file storage usage.
![image](https://github.com/user-attachments/assets/7d2ad5d9-7dd7-415d-8b30-a5258defb204)

**Comment by uncomfyhalomacro** [comment]
Looking at your logs again, it seems the archiving + compressing process is where the actual issue starts.

Still not sure how it affects your storage...

**Comment by uncomfyhalomacro** [comment]
@mantarimay I found the culprit based on your log.

```
tmpfs           1.9G   20K  1.9G   1% /tmp
```

I will provide a fix tonight if I have the time.

**Comment by uncomfyhalomacro** [comment]
Documented as an error message at 951b67a6ea66f0aae510d4c82ac768af5af972d5
